---
- name: Project 02 - Update Operational System | All - Test Internet Access
  uri:
    url: "https://google.com"

- name: Project 02 - Update Operational System | CentOS Like - Install epel-repository
  yum: name=epel-release state=latest
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Project 02 - Update Operational System | CentOS Like - Enable PowerTool Repository
  replace:
      dest=/etc/yum.repos.d/CentOS-Linux-PowerTools.repo
      regexp='enabled=0'
      replace='enabled=1'
  when: ansible_distribution_major_version == "8"

- name: Project 02 - Update Operational System | CentOS Like - Update System
  yum: name=* state=latest update_cache=yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  notify:
    - "Project 02 - Update Operational System | Reboot Target"
    - "Project 02 - Update Operational System | Wait Reboot"

- name: Project 02 - Update Operational System | Debian Like - Update Cache
  apt: update_cache=yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Project 02 - Update Operational System | Debian Like - Update System
  apt: name="*" state=latest
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  notify:
    - "Project 02 - Update Operational System | Reboot Target"
    - "Project 02 - Update Operational System | Wait Reboot"
...